/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pos.view;

import java.awt.Color;
import javax.swing.JOptionPane;
import pos.model.PasswordUtils;
import pos.model.Usuario;
import pos.util.Config;

/**
 *
 * @author Darío Jiménez
 */
public class ActPass extends javax.swing.JDialog {

    /**
     * Creates new form ActPass
     */
    private Usuario sesion;
    
    
    public ActPass(java.awt.Frame parent, boolean modal, Usuario in) {
        super(parent, modal);
        initComponents();
        
        sesion = in;
        
        
        getContentPane().setBackground(Color.decode(Config.ColorContent));
        jButton1.setBackground(Color.decode(Config.ColorElement));
        
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        passnew = new javax.swing.JPasswordField();
        passrep = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nueva contraseña");
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(350, 170));
        setPreferredSize(new java.awt.Dimension(350, 170));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel1.setText("Nueva contraseña");

        passnew.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N

        passrep.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel2.setText("Repetir contraseña");

        jButton1.setBackground(new java.awt.Color(114, 151, 166));
        jButton1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passnew, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                    .addComponent(passrep))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(131, 131, 131))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(passnew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passrep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String myPass1 = String.valueOf(passnew.getPassword());
        String myPass2 = String.valueOf(passrep.getPassword());        
        
        if(myPass1.compareTo("") == 0){
            JOptionPane.showMessageDialog(this, "El password no puede ser vacio");
            return;
        }
        if(myPass1.compareTo(myPass2) != 0){
            JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden");
            return;
        }
        
        //Recuperamos la semilla
        //String salt = PasswordUtils.getSalt(30);        
        String newPass = PasswordUtils.generateSecurePassword(myPass1, sesion.getSalt());
        
        //Usuario user = new Usuario("Admin", newPass, salt);
        if(Usuario.updatePass(sesion.getUser(), newPass, sesion.getSalt())){
            JOptionPane.showMessageDialog(this, "Se actualizó la contraseña correctamente");
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(this, "Se presento un problema al actualizar la contraseña");
        }        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField passnew;
    private javax.swing.JPasswordField passrep;
    // End of variables declaration//GEN-END:variables
}
